name: Language Stats
on:
  push:
    branches:
      - master
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Analyze Repository
        uses: https://github.com/juwenzhang/language-stats@v0.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
